// Nomad Outdoors event board: Cloudflare Worker + D1.
// Bindings needed: D1 database bound as DB, secret ORGANISER_CODE.
// The page, manifest and icons are embedded below (generated by build.py).

const HTML = __HTML__;
const HOME = __HOME__;
const ROUTES_PAGE = __ROUTES_PAGE__;
const ROUTE_PAGE = __ROUTE_PAGE__;
const ICONS = __ICONS__;

const MANIFEST = JSON.stringify({
  name: "Nomad Outdoors",
  short_name: "Nomad",
  start_url: "/board",
  display: "standalone",
  background_color: "#EDF0EC",
  theme_color: "#17201E",
  icons: [
    { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
    { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" }
  ]
});

const EVENT_FIELDS = {
  title: 70, type: 20, difficulty: 20, date: 10, endDate: 10, meetTime: 5, meetPoint: 90, mapLink: 500,
  radio: 40, destination: 90, requirement: 90, organiser: 60, details: 1500, kit: 1200, sponsorName: 60, sponsorOffer: 160
};
const TYPES = ["desert", "wadi", "camping", "overland", "social"];
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

let schemaReady = false;

export default {
  async fetch(req, env) {
    const url = new URL(req.url);
    const path = url.pathname;
    try {
      if (path.startsWith("/api/")) return await handleApi(req, env, path);
      if (path === "/manifest.webmanifest") return new Response(MANIFEST, { headers: { "content-type": "application/manifest+json", "cache-control": "public, max-age=86400" } });
      const icon = { "/icon-192.png": "i192", "/icon-512.png": "i512", "/apple-touch-icon.png": "i180", "/favicon.ico": "i192", "/og-image.png": "og" }[path];
      if (icon) return new Response(b64(ICONS[icon]), { headers: { "content-type": "image/png", "cache-control": "public, max-age=604800" } });
      if (path === "/" || path === "/index.html" || path === "/board" || path === "/board/") {
        const page = path.startsWith("/board") ? HTML : HOME;
        return new Response(page.replaceAll("__ORIGIN__", url.origin), { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-cache", "x-content-type-options": "nosniff", "referrer-policy": "same-origin" } });
      }
      if (path === "/robots.txt") return new Response("User-agent: *\nAllow: /\nDisallow: /board\nDisallow: /api/\nSitemap: " + url.origin + "/sitemap.xml\n", { headers: { "content-type": "text/plain" } });
      if (path.startsWith("/data/") || path === "/sitemap.xml") {
        if (!env.ASSETS) return new Response("Not found", { status: 404 });
        return env.ASSETS.fetch(req);
      }
      if (path === "/routes" || path === "/routes/") {
        const index = await asset(env, url, "/data/routes/index.json");
        if (!index) return Response.redirect(url.origin + "/", 302);
        const t = index.totals;
        const desc = `${t.routes} off-road routes and ${t.distance_km.toLocaleString("en-GB")} km of tracks from Nomad Outdoors drives across ${t.countries.join(" and ")}, with maps, elevation and GPX downloads.`;
        return page(fill(ROUTES_PAGE, { __ORIGIN__: url.origin, __DESC__: escHtml(desc) }, index));
      }
      const m = /^\/routes\/([a-z0-9-]+)\/?$/.exec(path);
      if (m) {
        const r = await asset(env, url, `/data/routes/${m[1]}.json`);
        if (!r) return Response.redirect(url.origin + "/routes", 302);
        const hrs = r.moving_min >= 60 ? `${Math.floor(r.moving_min / 60)} h ${r.moving_min % 60} min` : `${r.moving_min} min`;
        const desc = `${r.distance_km} km off-road route${r.area ? " in " + r.area : ""}${r.country ? ", " + r.country : ""}. ${hrs} moving, ${r.ascent_m} m of climb. Map, elevation profile and GPX download.`;
        return page(fill(ROUTE_PAGE, { __ORIGIN__: url.origin, __TITLE__: escHtml(r.title), __SLUG__: r.slug, __DESC__: escHtml(desc) }, r));
      }
      return Response.redirect(url.origin + "/", 302);
    } catch (e) {
      if (e instanceof ApiError) return json({ error: e.code, message: e.message }, e.status);
      console.error(e);
      return json({ error: "server", message: "Something went wrong on our side. Try again in a minute." }, 500);
    }
  }
};

class ApiError extends Error {
  constructor(status, code, message) { super(message); this.status = status; this.code = code; }
}

async function handleApi(req, env, path) {
  if (!env.DB) throw new ApiError(500, "no_database", "The board isn't connected to its database yet.");
  await ensureSchema(env.DB);
  const db = env.DB;
  const organiser = isOrganiser(req, env);

  if (req.method === "GET" && path === "/api/board") {
    const viewer = normalisePhone(req.headers.get("x-phone") || "");
    const ev = await db.prepare("SELECT id, data FROM events WHERE date >= date('now','-180 days') ORDER BY date LIMIT 300").all();
    const events = ev.results.map(r => ({ ...JSON.parse(r.data), id: r.id }));
    const ids = new Set(events.map(e => e.id));
    const su = await db.prepare("SELECT event_id, phone, name, vehicle, people, bringing, note, created_at FROM signups ORDER BY created_at").all();
    const signups = su.results.filter(r => ids.has(r.event_id)).map(r => {
      const s = { eventId: r.event_id, name: r.name, vehicle: r.vehicle || "", people: r.people || 1, bringing: r.bringing || "", note: r.note || "", at: r.created_at, mine: !!viewer && r.phone === viewer };
      if (organiser) s.phone = r.phone;
      return s;
    });
    return json({ events, signups, organiser });
  }

  if (req.method !== "POST") throw new ApiError(405, "method", "Not allowed.");
  const body = await readBody(req);

  switch (path) {
    case "/api/organiser": {
      if (!orgCode(env)) throw new ApiError(500, "no_code", "No organiser code has been set up yet. Add ORGANISER_CODE under Production settings and redeploy.");
      if (!safeEqual(String(body.code || "").trim(), orgCode(env))) throw new ApiError(403, "bad_code", "That code isn't right. Check with Richard.");
      return json({ ok: true });
    }

    case "/api/phone": {
      const phone = normalisePhone(body.phone);
      if (!phone) throw new ApiError(400, "bad_phone", "That doesn't look like a mobile number. Try 050 123 4567 or +971 50 123 4567.");
      return json({ phone });
    }

    case "/api/signup": {
      const eventId = String(body.eventId || "");
      const phone = normalisePhone(body.phone);
      const name = clip(body.name, 60);
      if (!name) throw new ApiError(400, "no_name", "Add your name so people know who's coming.");
      if (!phone) throw new ApiError(400, "bad_phone", "That doesn't look like a mobile number. Try 050 123 4567 or +971 50 123 4567.");
      const row = await db.prepare("SELECT data FROM events WHERE id = ?").bind(eventId).first();
      if (!row) throw new ApiError(404, "no_event", "That event has been removed.");
      const ev = JSON.parse(row.data);
      if ((ev.endDate || ev.date) < todayDubai()) throw new ApiError(400, "past", "That event has already happened.");
      const people = Math.max(1, Math.min(12, parseInt(body.people, 10) || 1));
      const now = new Date().toISOString();
      await db.prepare(
        `INSERT INTO signups (event_id, phone, name, vehicle, people, bringing, note, created_at, updated_at)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?8)
         ON CONFLICT(event_id, phone) DO UPDATE SET name = excluded.name, vehicle = excluded.vehicle, people = excluded.people,
           bringing = excluded.bringing, note = excluded.note, updated_at = excluded.updated_at`
      ).bind(eventId, phone, name, clip(body.vehicle, 60), people, clip(body.bringing, 80), clip(body.note, 120), now).run();
      let waitlisted = false;
      const cap = Number(ev.capacity) || 0;
      if (cap) {
        const pos = await db.prepare("SELECT COUNT(*) AS n FROM signups WHERE event_id = ?1 AND created_at <= (SELECT created_at FROM signups WHERE event_id = ?1 AND phone = ?2)").bind(eventId, phone).first();
        waitlisted = pos.n > cap;
      }
      return json({ ok: true, phone, waitlisted });
    }

    case "/api/cancel": {
      const phone = normalisePhone(body.phone);
      if (!phone) throw new ApiError(400, "bad_phone", "We couldn't tell who you are on this phone. Use 'Enter your number' at the bottom of the page.");
      const r = await db.prepare("DELETE FROM signups WHERE event_id = ? AND phone = ?").bind(String(body.eventId || ""), phone).run();
      if (!r.meta.changes) throw new ApiError(404, "not_found", "We couldn't find your sign-up for this event.");
      return json({ ok: true });
    }

    case "/api/events": {
      if (!organiser) throw new ApiError(403, "not_organiser", "Only organisers can post events. Log in with the organiser code first.");
      const data = {};
      for (const [k, max] of Object.entries(EVENT_FIELDS)) data[k] = clip(body[k], max);
      data.capacity = Math.max(0, Math.min(60, parseInt(body.capacity, 10) || 0));
      if (!TYPES.includes(data.type)) data.type = "social";
      if (!data.title) throw new ApiError(400, "no_title", "Give the event a name.");
      if (!DATE_RE.test(data.date)) throw new ApiError(400, "bad_date", "Pick a date.");
      if (data.endDate && (!DATE_RE.test(data.endDate) || data.endDate < data.date)) throw new ApiError(400, "bad_end", "The end date is before the start date.");
      if (data.mapLink && !/^https?:\/\//i.test(data.mapLink)) throw new ApiError(400, "bad_map", "The map link should start with https://");
      const now = new Date().toISOString();
      let id = String(body.id || "");
      if (id) {
        const old = await db.prepare("SELECT data FROM events WHERE id = ?").bind(id).first();
        if (!old) throw new ApiError(404, "no_event", "That event has been removed.");
        const merged = { ...JSON.parse(old.data), ...data, updatedAt: now };
        await db.prepare("UPDATE events SET date = ?, data = ?, updated_at = ? WHERE id = ?").bind(data.date, JSON.stringify(merged), now, id).run();
      } else {
        id = crypto.randomUUID().replace(/-/g, "").slice(0, 12);
        await db.prepare("INSERT INTO events (id, date, data, created_at, updated_at) VALUES (?, ?, ?, ?, ?)").bind(id, data.date, JSON.stringify({ ...data, createdAt: now }), now, now).run();
      }
      return json({ ok: true, id });
    }

    case "/api/events/delete": {
      if (!organiser) throw new ApiError(403, "not_organiser", "Only organisers can delete events.");
      const id = String(body.id || "");
      await db.batch([
        db.prepare("DELETE FROM signups WHERE event_id = ?").bind(id),
        db.prepare("DELETE FROM events WHERE id = ?").bind(id)
      ]);
      return json({ ok: true });
    }
  }
  throw new ApiError(404, "not_found", "Not found.");
}

async function ensureSchema(db) {
  if (schemaReady) return;
  await db.batch([
    db.prepare("CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, date TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)"),
    db.prepare("CREATE TABLE IF NOT EXISTS signups (event_id TEXT NOT NULL, phone TEXT NOT NULL, name TEXT NOT NULL, vehicle TEXT, people INTEGER NOT NULL DEFAULT 1, bringing TEXT, note TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (event_id, phone))")
  ]);
  schemaReady = true;
}

function isOrganiser(req, env) {
  const code = (req.headers.get("x-organiser-code") || "").trim();
  return !!orgCode(env) && !!code && safeEqual(code, orgCode(env));
}

function orgCode(env) { return String(env.ORGANISER_CODE || "").trim(); }

function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let d = 0;
  for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return d === 0;
}

// UAE-friendly: 050 123 4567 -> +971501234567; 00xx -> +xx; +xx kept.
function normalisePhone(raw) {
  let p = String(raw || "").trim().replace(/[\s\-().]/g, "");
  if (!p) return "";
  if (p.startsWith("00")) p = "+" + p.slice(2);
  if (/^0\d{8,9}$/.test(p)) p = "+971" + p.slice(1);
  else if (/^5\d{8}$/.test(p)) p = "+971" + p;
  else if (/^971\d{8,9}$/.test(p)) p = "+" + p;
  return /^\+\d{8,15}$/.test(p) ? p : "";
}

function todayDubai() {
  return new Date(Date.now() + 4 * 3600 * 1000).toISOString().slice(0, 10);
}

function clip(v, max) { return String(v ?? "").trim().slice(0, max); }

async function readBody(req) {
  const len = Number(req.headers.get("content-length") || 0);
  if (len > 20000) throw new ApiError(413, "too_big", "That's too much text.");
  try { return await req.json(); } catch { throw new ApiError(400, "bad_json", "Something went wrong sending that. Try again."); }
}

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), { status, headers: { "content-type": "application/json", "cache-control": "no-store" } });
}

async function asset(env, url, p) {
  if (!env.ASSETS) return null;
  const res = await env.ASSETS.fetch(new Request(url.origin + p));
  if (!res.ok) return null;
  try { return await res.json(); } catch { return null; }
}

function fill(tpl, vars, data) {
  let html = tpl;
  for (const [k, v] of Object.entries(vars)) html = html.replaceAll(k, v);
  // __DATA__ last, so nothing inside the data is treated as a placeholder
  return html.replace("__DATA__", () => JSON.stringify(data).replace(/</g, "\\u003c"));
}

function page(html) {
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300", "x-content-type-options": "nosniff" } });
}

function escHtml(s) {
  return String(s ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function b64(s) {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
